name: Build Alpine containers

on:
  push:
    branches: master

env:
  WATCHMAN_VERSION: "v2021.02.01.00"

jobs:
  alpine-3-10:
    name: Build alpine 3.10
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          file: ./alpine/3.10/Dockerfile
          tags: "janarj/watchman:alpine-3.10-$WATCHMAN_VERSION"
          build-args: |
            WATCHMAN_VERSION=$WATCHMAN_VERSION


  alpine-3-11:
    name: Build alpine 3.11
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          file: ./alpine/3.11/Dockerfile
          tags: "janarj/watchman:alpine-3.11-$WATCHMAN_VERSION"
          build-args: |
            WATCHMAN_VERSION=$WATCHMAN_VERSION


  alpine-3-12:
    name: Build alpine 3.12
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          file: ./alpine/3.12/Dockerfile
          tags: "janarj/watchman:alpine-3.12-$WATCHMAN_VERSION"
          build-args: |
            WATCHMAN_VERSION=$WATCHMAN_VERSION


  alpine-3-13:
    name: Build alpine 3.13
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          file: ./alpine/3.13/Dockerfile
          tags: "janarj/watchman:alpine-3.13-$WATCHMAN_VERSION"
          build-args: |
            WATCHMAN_VERSION=$WATCHMAN_VERSION
