name: Build Debian containers

on:
  push:
    branches: master

env:
  WATCHMAN_VERSION: "v2021.02.01.00"

jobs:
  alpine:
    name: Build alpine
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Debian Buster
        uses: docker/build-push-action@v2
        with:
          push: true
          file: ./debian/buster/Dockerfile
          # Will be enabled once Dockerfile configured to build from sources
          # platforms: linux/386,linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64,linux/ppc64le,linux/s390x
          tags: |
            janarj/watchman:debian-buster-${{ env.WATCHMAN_VERSION }}
            janarj/watchman:debian-buster
            janarj/watchman:debian
          build-args: |
            WATCHMAN_VERSION=${{ env.WATCHMAN_VERSION }}
